apiVersion: v1
kind: ConfigMap
metadata:
  name: split-inference-config
data:
  config.yaml: |
    name: YOLO
    server:
      cut-layer: a #or b, c
      clients:
        - 1
        - 1
      model: yolov8n
      batch-frame: 1
    rabbit:
      address: rabbitmq-service
      username: admin
      password: admin
      virtual-host: /

    data: /app/video.mp4
    log-path: .
    control-count: 10
    debug-mode: False
