apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-inference-server
  labels:
    app: split-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: split-inference-server
  template:
    metadata:
      labels:
        app: split-inference-server
    spec:
      containers:
      - name: server
        image: quang47/inference_server:v5
        imagePullPolicy: Always
        command: ["python", "server.py"]
        ports:
        - containerPort: 5672
          name: amqp
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: logs-volume
          mountPath: /app/logs
        env:
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "300Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "300m"
      volumes:
      - name: config-volume
        configMap:
          name: split-inference-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: split-inference-server
  labels:
    app: split-inference-server
spec:
  selector:
    app: split-inference-server
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  type: ClusterIP 