apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-inference-layer2
  labels:
    app: split-inference-layer2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: split-inference-layer2
  template:
    metadata:
      labels:
        app: split-inference-layer2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: layer2
        image: quang47/inference_client:v5
        imagePullPolicy: Always
        command: ["python", "client.py", "--layer_id", "2", "--device", "cpu"]
        ports:
        - containerPort: 8002
          name: metrics
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: logs-volume
          mountPath: /app/logs
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: PROMETHEUS_PORT
          value: "8002"
        resources:
          requests:
            memory: "800Mi"
            cpu: "600m"
          limits:
            memory: "2Gi"
            cpu: "2"
      volumes:
      - name: config-volume
        configMap:
          name: split-inference-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: split-inference-layer2
  namespace: default
  labels:
    app: split-inference-layer2
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8002"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: split-inference-layer2
  ports:
  - port: 8002
    targetPort: 8002
    name: metrics
  type: ClusterIP 