apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: split-inference-layer2-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: split-inference-layer2
  minReplicas: 1 
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max 
    scaleDown:
      stabilizationWindowSeconds: 120 
      policies:
      - type: Percent
        value: 100 
        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 15