apiVersion: apps/v1
kind: Deployment
metadata:
  name: split-inference-server
  labels:
    app: split-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: split-inference-server
  template:
    metadata:
      labels:
        app: split-inference-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: server
        image: quang47/inference_server
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep 10 && python server.py"]
        ports:
        - containerPort: 8000
          name: metrics
        - containerPort: 5672
          name: amqp
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        - name: logs-volume
          mountPath: /app/logs
        env:
        - name: PYTHONPATH
          value: "/app"
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "800m"
      volumes:
      - name: config-volume
        configMap:
          name: split-inference-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: split-inference-server
  labels:
    app: split-inference-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: split-inference-server
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
  - port: 5672
    targetPort: 5672
    name: amqp
  type: ClusterIP 