name: YOLO
server:
  cut-layer: a #or b, c
  clients:
    - 1
    - 1
  model: yolov8n
  batch-frame: 1
rabbit:
  address: rabbitmq
  username: admin
  password: admin
  virtual-host: /

data: http://video_server:5000/video
log-path: .
control-count: 10
debug-mode: False
