name: YOLO
server:
  cut-layer: a #or b, c
  clients:
    - 1
    - 1
  model: yolov8n
  batch-frame: 1
rabbit:
  address: rabbitmq
  username: admin
  password: admin
  virtual-host: /
  prefetch-count: 5

data: http://video-server.default.svc.cluster.local:5000/video
log-path: .
debug-mode: False
